"""
{{project_name}} — KnowScraper Project
Generated by: knowscraper create

Crawler type: PlaywrightCrawler (real browser automation)
Best for: JavaScript-heavy sites, SPAs, sites with anti-bot protection.
"""

import asyncio
from knowscraper import PlaywrightCrawler, Router, Dataset

router = Router()
dataset = Dataset(name="results")


@router.default_handler
async def handle_page(ctx):
    ctx.log.info(f"Browser visiting: {ctx.request.url}")

    # Use Playwright page API directly
    title = await ctx.page.title()

    # TODO: replace with your actual selectors
    # items = await ctx.page.query_selector_all(".item")
    # for item in items:
    #     text = await item.inner_text()
    #     await dataset.push_data({"text": text, "url": ctx.request.url})

    await dataset.push_data({
        "title": title,
        "url": ctx.request.url,
    })

    # Follow links (optional)
    # await ctx.enqueue_links(selector="a[href]")


async def main():
    crawler = PlaywrightCrawler(
        router=router,
        dataset=dataset,
        browser_type="chromium",
        headless=True,
        stealth_mode=True,
        inject_fingerprint=True,
        max_concurrency=2,
        respect_robots_txt=True,
        use_anti_detection=True,
    )

    # TODO: replace with your start URL(s)
    await crawler.run(["https://example.com"])

    print(f"\nDone! Collected {dataset.count} items")
    await dataset.export_to_json()
    await dataset.export_to_csv()


if __name__ == "__main__":
    asyncio.run(main())
