"""
{{project_name}} — KnowScraper Project
Generated by: knowscraper create

Crawler type: CheerioCrawler (HTTP + HTML parsing, no browser)
Best for: static sites, blogs, e-commerce without JavaScript rendering.
"""

import asyncio
from knowscraper import CheerioCrawler, Router, Dataset

router = Router()
dataset = Dataset(name="results")


@router.default_handler
async def handle_page(ctx):
    ctx.log.info(f"Scraping: {ctx.request.url}")

    # TODO: replace with your actual selectors
    for item in ctx.parsed.select(".item"):
        title = item.select_one(".title")
        if title:
            await dataset.push_data({
                "title": title.get_text(strip=True),
                "url": ctx.request.url,
            })

    # Follow pagination or next links
    # await ctx.enqueue_links(selector="a.next", label="listing")


async def main():
    crawler = CheerioCrawler(
        router=router,
        dataset=dataset,
        max_concurrency=5,
        min_delay=0.5,
        max_delay=1.5,
        respect_robots_txt=True,
        use_anti_detection=True,
    )

    # TODO: replace with your start URL(s)
    await crawler.run(["https://example.com"])

    print(f"\nDone! Collected {dataset.count} items")
    await dataset.export_to_json()
    await dataset.export_to_csv()


if __name__ == "__main__":
    asyncio.run(main())
